### ISSUE TITLE
Assign new issues to a project

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1394]
When a new issue is created in the repo, it should be assigned to a project automatically.

Quick googling showed this [Stackoverflow post](https://stackoverflow.com/questions/62530078/github-auto-assign-issue-to-project)
Other action: https://github.com/srggrs/assign-one-project-github-action

```
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: My project
          column-name: My column
```

Make sure to pin non-verified GHA to a specific git SHA that has been verified.
