### ISSUE TITLE
MS build setup does not create releases

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry-dotnet#3790]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

8.0

### OS

Android

### SDK Version

4.10.0

### Steps to Reproduce

The user is trying to create a Release from Azure Dev Ops pipeline for their MAUI project. They have followed [this article](https://docs.sentry.io/platforms/dotnet/configuration/msbuild/).

The pipeline is now succeeding but the release never gets created. At the end of the logs they see the following warning:
```
(_CreateSentryRelease target) ->
EXEC : warning : An organization ID or slug is required (provide with --org) [/Users/(...).Maui.csproj::TargetFramework=net8.0-ios]

"/Users/(...).sln" (Publish target) (1) ->
"/Users/(...).Maui.csproj" (Publish target) (11) ->
(_SentrySetCommits target) ->
EXEC : warning : An organization ID or slug is required (provide with --org) [/Users/(...).Maui.csproj::TargetFramework=net8.0-ios]
```

They are specifying the org and project. Here is the YAML when they try and build for Android:
```yml
- task: DotNetCoreCLI@2
displayName: 'Build and sign Android target'
inputs:
command: 'publish'
projects: '**/(...).Maui.csproj'
publishWebProjects: false
zipAfterPublish: False
arguments: '-c $(buildConfiguration) -f net8.0-android -o $(outputDirectory) -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=D:\a\1\s\(...).keystore -p:AndroidSigningStorePass=password -p:AndroidSigningKeyAlias=(...) -p:AndroidSigningKeyPass=password -p:SentryOrg=(...) -p:SentryProject=(...) /p:ApplicationDisplayVersion=$(fullBuildVersionString) /p:ApplicationVersion=$(Build.BuildID)'
env:
SENTRY_RELEASE : $(fullBuildVersionString)
SENTRY_AUTH_TOKEN: '(...)'
```

They have also tried setting them in the csproj:
```xml
<PropertyGroup Condition="'$(Configuration)' == 'Release' Or '$(Configuration)' == 'ReleaseLiveConfig'">

<!-- Configure Sentry org and project -->
<SentryOrg>(...)</SentryOrg>
<SentryProject>(...)</SentryProject>

<!-- Automatically creates a release when building your application. -->
<SentryCreateRelease>true</SentryCreateRelease>

<!-- Automatically associates commits with the release. -->
<SentrySetCommits>true</SentrySetCommits>

<!-- Optionally provide explicit flags to the set-commits command -->
<SentrySetCommitOptions>--local</SentrySetCommitOptions>

<!-- Sends symbols to Sentry, enabling symbolication of stack traces. -->
<SentryUploadSymbols>true</SentryUploadSymbols>

<!-- Sends sources to Sentry, enabling display of source context. -->
<SentryUploadSources>true</SentryUploadSources>

<!-- If you are targeting Android, sends proguard mapping file to Sentry. -->
<SentryUploadAndroidProguardMapping>true</SentryUploadAndroidProguardMapping>

</PropertyGroup>
```

### Expected Result

A release is created in Sentry's releases tab.

### Actual Result

They can see in the logs what looks like a successful upload of the "debug information files" but no release.

Creating a `.sentryclirc` file or using `sentry-cli login` did not help.

More logs and config without scrubbing in the shadow ticket.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2362) by [Unito](https://www.unito.io)
